In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("dataset.csv")
fraud_probability = df["fraud_probability"]
print("Laundering typology tells us what kind of fraud was performed.")
(((df["is_fraud"] == 0) == (df["laundering_typology"] == "normal")) & ((df["is_fraud"] == 1) == (df["laundering_typology"] != "normal"))).all()

Laundering typology tells us what kind of fraud was performed.

np.True_

In [3]:
df = df.drop(columns = ["fraud_probability", "laundering_typology"])
df.columns

Index(['type', 'category', 'orig', 'dest', 'old_balance', 'new_balance',
       'is_fraud', 'payment_method', 'location.city', 'location.state',
       'location.postcode', 'device_info.type', 'device_info.os',
       'device_info.ip_address', 'risk_indicators.amount_vs_average',
       'risk_indicators.customer_risk_score', 'risk_indicators.category_risk',
       'risk_indicators.risk_score', 'risk_indicators.unusual_time',
       'risk_indicators.unusual_location', 'merchant_info.merchant_id',
       'merchant_info.category', 'merchant_info.risk_level',
       'merchant_info.avg_transaction', 'datetime'],
      dtype='str')

1. Location preprocessing. Every city belongs to a unique state. Therefore we combine city and state and create a single categorical column. Use relative frequencies for postcodes.

In [4]:
df["city_state"] = (df["location.city"] + "_" + df["location.state"]).astype("category").cat.codes
df["postcode"] = df["location.postcode"]
df = df.drop(columns = ["location.city", "location.state", "location.postcode"])
print(f"Number of unique cities: {df["city_state"].nunique()}")

Number of unique cities: 6

2. Device type preprocessing. We combine type and os and create a single categorical column. Use subnet (for example 192.168.1.5 -> 192.168) for ip addresses, and then convert them to categories.

In [5]:
df["device"] = (df["device_info.type"] + "_" + df["device_info.os"]).astype("category").cat.codes
print(f"Number of unique devices: {df["device"].nunique()}")
df["ip_subnet"] = df["device_info.ip_address"].astype(str).str.extract(r"^(\d+\.\d+)")[0]
df["ip_subnet"] = df["ip_subnet"].astype("category").cat.codes
print(f"Number of unique ip addresses: {df["device_info.ip_address"].nunique()}")
print(f"Number of unique ip subnets: {df["ip_subnet"].nunique()}")
subnets_per_orig = df.groupby("orig")["ip_subnet"].nunique()
print(f"Average subnets per user: {subnets_per_orig.mean()}")
print(f"Users with only 1 subnet: {(subnets_per_orig == 1).sum()}")

Number of unique devices: 12
Number of unique ip addresses: 1090043
Number of unique ip subnets: 64516
Average subnets per user: 108.9081
Users with only 1 subnet: 0

In [6]:
df = df.drop(columns = ["device_info.type", "device_info.os", "device_info.ip_address"])

3. Convert type, category, and payment_method into categorical data.

In [7]:
df["type"] = df["type"].astype("category").cat.codes
df["category"] = df["category"].astype("category").cat.codes
df["payment_method"] = df["payment_method"].astype("category").cat.codes
print(f"Number of unique types: {df["type"].nunique()}")
print(f"Number of unique categories: {df["category"].nunique()}")
print(f"Number of unique payment methods: {df["payment_method"].nunique()}")

Number of unique types: 8
Number of unique categories: 11
Number of unique payment methods: 3

4. Analysis of risk_indicator columns, as they are the outputs of the AMLNet models.

In [8]:
risk_columns = [c for c in df.columns if c.startswith("risk_indicators.")]
temp_df = df[risk_columns + ["is_fraud"]].copy()

temp_df["risk_indicators.category_risk"] = temp_df["risk_indicators.category_risk"].astype("category").cat.codes
temp_df["risk_indicators.unusual_time"] = temp_df["risk_indicators.unusual_time"].astype("category").cat.codes
temp_df["risk_indicators.unusual_location"] = temp_df["risk_indicators.unusual_location"].astype("category").cat.codes

leakage_analysis = temp_df.corr()["is_fraud"].drop("is_fraud").sort_values(ascending=False)
leakage_analysis

risk_indicators.amount_vs_average      0.106359
risk_indicators.risk_score             0.078350
risk_indicators.category_risk          0.045435
risk_indicators.customer_risk_score   -0.047015
risk_indicators.unusual_time                NaN
risk_indicators.unusual_location            NaN
Name: is_fraud, dtype: float64

Risk indicators are still the results of the AMLNet models, and therefore they should be removed from our baseline model.

In [9]:
df = df.drop(columns = risk_columns)
df.head()

,type,category,orig,dest,old_balance,new_balance,is_fraud,payment_method,merchant_info.merchant_id,merchant_info.category,merchant_info.risk_level,merchant_info.avg_transaction,datetime,city_state,postcode,device,ip_subnet
0,2,5,C8083,C7053,455489.321571,455190.479531,0,0,NaN,NaN,NaN,NaN,2025-02-04 12:22:36,5,2755,6,3021
1,2,7,C5575,C1117,229508.291214,229415.203298,0,1,NaN,NaN,NaN,NaN,2025-02-04 12:44:31,1,4976,8,30776
2,3,3,C1549,C1423,202568.806856,202413.161992,0,2,NaN,NaN,NaN,NaN,2025-02-04 12:48:01,5,2927,6,23741
3,0,2,C7435,C6390,491560.600203,491260.841131,0,1,NaN,NaN,NaN,NaN,2025-02-04 12:57:48,5,2332,5,43287
4,2,5,C8083,C5946,455190.479531,455016.763916,0,1,NaN,NaN,NaN,NaN,2025-02-04 12:58:37,5,2572,10,4091

5. Merchant information.

In [10]:
merchant_cols = [col for col in df.columns if "merchant_info" in col]
df.loc[df["merchant_info.merchant_id"].notna(), merchant_cols].head(1)

,merchant_info.merchant_id,merchant_info.category,merchant_info.risk_level,merchant_info.avg_transaction
5,M389,Housing,low,2000.0

In [11]:
df["merchant_info.merchant_id"] = df["merchant_info.merchant_id"].astype("category").cat.codes.replace(-1, np.nan)
df["merchant_info.category"] = df["merchant_info.category"].astype("category").cat.codes.replace(-1, np.nan)
df["merchant_info.risk_level"] = df["merchant_info.risk_level"].astype("category").cat.codes.replace(-1, np.nan)
print(f"Number of unique merchant ids: {df["merchant_info.merchant_id"].nunique()}")
print(f"Number of unique categories: {df["merchant_info.category"].nunique()}")
print(f"Number of unique risks levels: {df["merchant_info.risk_level"].nunique()}")
df.loc[df["merchant_info.merchant_id"].notna(), merchant_cols].head(1)

Number of unique merchant ids: 1000
Number of unique categories: 6
Number of unique risks levels: 3

,merchant_info.merchant_id,merchant_info.category,merchant_info.risk_level,merchant_info.avg_transaction
5,322.0,2.0,1.0,2000.0

6. Time-series and feature engineering.

In [12]:
all_accounts = np.concatenate([df["orig"].values, df["dest"].values])
print(all_accounts.shape)
_, integer_mapping = np.unique(all_accounts, return_inverse = True)
df["orig"] = integer_mapping[:len(df)]
df["dest"] = integer_mapping[len(df):]

(2180344,)

In [13]:
df["datetime"] = pd.to_datetime(df["datetime"])
df = df.sort_values("datetime").reset_index(drop = True)

# Transform hours (in a day) into sin/cos
df["hour_sin"] = np.sin(2 * np.pi * df["datetime"].dt.hour/24)
df["hour_cos"] = np.cos(2 * np.pi * df["datetime"].dt.hour/24)

# Transform days (in a week) into sin/cos
df["day_sin"] = np.sin(2 * np.pi * df["datetime"].dt.dayofweek/7)
df["day_cos"] = np.cos(2 * np.pi * df["datetime"].dt.dayofweek/7)

# Transform months (in a year) into sin/cos
df["month_sin"] = np.sin(2 * np.pi * df["datetime"].dt.month/12)
df["month_cos"] = np.cos(2 * np.pi * df["datetime"].dt.month/12)

df.head()

,type,category,orig,dest,old_balance,new_balance,is_fraud,payment_method,merchant_info.merchant_id,merchant_info.category,...,city_state,postcode,device,ip_subnet,hour_sin,hour_cos,day_sin,day_cos,month_sin,month_cos
0,2,2,2757,982,394437.711297,394176.204794,0,1,NaN,NaN,...,2,3740,5,10831,0.258819,-0.965926,0.781831,0.62349,0.866025,0.5
1,2,7,5274,3316,319338.243872,319075.661365,0,2,NaN,NaN,...,4,6615,2,59095,0.258819,-0.965926,0.781831,0.62349,0.866025,0.5
2,2,5,5539,9714,456079.479098,455716.291490,0,0,NaN,NaN,...,1,4554,7,27230,0.258819,-0.965926,0.781831,0.62349,0.866025,0.5
3,0,4,9843,10665,435461.552951,431760.321488,0,1,110.0,2.0,...,3,2105,10,46953,0.258819,-0.965926,0.781831,0.62349,0.866025,0.5
4,2,3,6751,9215,266064.478615,265913.074246,0,0,NaN,NaN,...,5,2529,4,834,0.258819,-0.965926,0.781831,0.62349,0.866025,0.5

In [14]:
df["amount"] = abs(df["old_balance"] - df["new_balance"])
windows = {"1h" : 1, "24h" : 24, "7d" : 168}

In [15]:
sends = df[["datetime", "orig", "dest", "amount"]].copy()
sends = sends.sort_values(["orig", "datetime"]).set_index("datetime")
for w, hrs in windows.items():
    roll = sends.groupby("orig")["amount"].rolling(w, closed = "left")
    # Count per the past window (excluding the current)
    sends[f"count_as_orig_{w}"] = roll.count().values
    # Mean per the past window (excluding the current)
    sends[f"mean_amt_as_orig_{w}"] = roll.mean().values
    roll_dest = sends.groupby("orig")["dest"].rolling(w, closed = "left")
    sends[f"unique_dest_{w}"] = roll_dest.apply(lambda x: len(np.unique(x)), raw = True).values
    
sends.head()

/var/folders/mc/6ndd_qgn5m16c5ygbjygfqj00000gn/T/ipykernel_99901/2140919684.py:4: Pandas4Warning: 'd' is deprecated and will be removed in a future version, please use 'D' instead.
  roll = sends.groupby("orig")["amount"].rolling(w, closed = "left")
/var/folders/mc/6ndd_qgn5m16c5ygbjygfqj00000gn/T/ipykernel_99901/2140919684.py:9: Pandas4Warning: 'd' is deprecated and will be removed in a future version, please use 'D' instead.
  roll_dest = sends.groupby("orig")["dest"].rolling(w, closed = "left")

,orig,dest,amount,count_as_orig_1h,mean_amt_as_orig_1h,unique_dest_1h,count_as_orig_24h,mean_amt_as_orig_24h,unique_dest_24h,count_as_orig_7d,mean_amt_as_orig_7d,unique_dest_7d
datetime,,,,,,,,,,,,
2025-02-06 09:00:22,0,512,42.440176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-02-07 09:02:42,0,9316,274.335162,NaN,NaN,NaN,NaN,NaN,NaN,1.0,42.440176,1.0
2025-02-07 18:51:35,0,10480,2518.720808,NaN,NaN,NaN,1.0,274.335162,1.0,2.0,158.387669,2.0
2025-02-13 07:36:34,0,10093,2233.866039,NaN,NaN,NaN,NaN,NaN,NaN,3.0,945.165382,3.0
2025-02-13 11:22:30,0,422,123.031109,NaN,NaN,NaN,1.0,2233.866039,1.0,3.0,1675.640670,3.0

In [16]:
sends["all_time_count_as_orig"] = sends.groupby("orig").cumcount().values

cum_sum = sends.groupby("orig")["amount"].cumsum().values
all_time_sum = cum_sum - sends["amount"].values

# Usual transaction amount per transaction = Sum_all / C_all
sends["usual_amt_as_orig"] = np.where(sends["all_time_count_as_orig"] > 0, all_time_sum / sends["all_time_count_as_orig"], np.nan)
    
sends = sends.reset_index()

first_timestamps = sends.groupby("orig")["datetime"].transform("first")

hours_active = (sends["datetime"] - first_timestamps).dt.total_seconds() / 3600.0

# Usual count per hour = C_all / T
sends["usual_count_per_hour_as_orig"] = np.where(hours_active > 0, sends["all_time_count_as_orig"] / hours_active, 0.0)

# Usual transaction amount per hour = Sum_all / T
sends["usual_volume_per_hour_as_orig"] = np.where(hours_active > 0, all_time_sum / hours_active, 0.0)

# Time since the last transaction 
sends["time_since_last_tx_as_orig"] = sends.groupby("orig")["datetime"].diff().dt.total_seconds()

In [17]:
sends = sends.drop(columns = ["amount", "dest"]).rename(columns = {"orig": "account"})
sends.head()

,datetime,account,count_as_orig_1h,mean_amt_as_orig_1h,unique_dest_1h,count_as_orig_24h,mean_amt_as_orig_24h,unique_dest_24h,count_as_orig_7d,mean_amt_as_orig_7d,unique_dest_7d,all_time_count_as_orig,usual_amt_as_orig,usual_count_per_hour_as_orig,usual_volume_per_hour_as_orig,time_since_last_tx_as_orig
0,2025-02-06 09:00:22,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0.000000,0.000000,NaN
1,2025-02-07 09:02:42,0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,42.440176,1.0,1,42.440176,0.041599,1.765480,86540.0
2,2025-02-07 18:51:35,0,NaN,NaN,NaN,1.0,274.335162,1.0,2.0,158.387669,2.0,2,158.387669,0.059078,9.357210,35333.0
3,2025-02-13 07:36:34,0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,945.165382,3.0,3,945.165382,0.018007,17.019444,477899.0
4,2025-02-13 11:22:30,0,NaN,NaN,NaN,1.0,2233.866039,1.0,3.0,1675.640670,3.0,4,1267.340546,0.023478,29.755211,13556.0

In [18]:
recvs = df[["datetime", "orig", "dest", "amount"]].copy()
recvs = recvs.sort_values(["dest", "datetime"]).set_index("datetime")
for w, hrs in windows.items():
    roll = recvs.groupby("dest")["amount"].rolling(w, closed = "left")
    # Count per the past window (excluding the current)
    recvs[f"count_as_dest_{w}"] = roll.count().values
    # Mean per the past window (excluding the current)
    recvs[f"mean_amt_as_dest_{w}"] = roll.mean().values
    roll_orig = recvs.groupby("dest")["orig"].rolling(w, closed = "left")
    recvs[f"unique_orig_{w}"] = roll_orig.apply(lambda x: len(np.unique(x)), raw = True).values
    
recvs.head()

/var/folders/mc/6ndd_qgn5m16c5ygbjygfqj00000gn/T/ipykernel_99901/1246052393.py:4: Pandas4Warning: 'd' is deprecated and will be removed in a future version, please use 'D' instead.
  roll = recvs.groupby("dest")["amount"].rolling(w, closed = "left")
/var/folders/mc/6ndd_qgn5m16c5ygbjygfqj00000gn/T/ipykernel_99901/1246052393.py:9: Pandas4Warning: 'd' is deprecated and will be removed in a future version, please use 'D' instead.
  roll_orig = recvs.groupby("dest")["orig"].rolling(w, closed = "left")

,orig,dest,amount,count_as_dest_1h,mean_amt_as_dest_1h,unique_orig_1h,count_as_dest_24h,mean_amt_as_dest_24h,unique_orig_24h,count_as_dest_7d,mean_amt_as_dest_7d,unique_orig_7d
datetime,,,,,,,,,,,,
2025-02-04 16:32:28,422,0,336.273038,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-02-04 17:26:29,5090,0,85.820226,1.0,336.273038,1.0,1.0,336.273038,1.0,1.0,336.273038,1.0
2025-02-05 01:19:07,422,0,59.036424,NaN,NaN,NaN,2.0,211.046632,2.0,2.0,211.046632,2.0
2025-02-05 05:28:56,422,0,195.914811,NaN,NaN,NaN,3.0,160.376563,2.0,3.0,160.376563,2.0
2025-02-09 19:35:44,7773,0,122.028023,NaN,NaN,NaN,NaN,NaN,NaN,4.0,169.261125,2.0

In [19]:
recvs["all_time_count_as_dest"] = recvs.groupby("dest").cumcount().values

cum_sum = recvs.groupby("dest")["amount"].cumsum().values
all_time_sum = cum_sum - recvs["amount"].values

# Usual transaction amount per transaction = Sum_all / C_all
recvs["usual_amt_as_dest"] = np.where(recvs["all_time_count_as_dest"] > 0, all_time_sum / recvs["all_time_count_as_dest"], np.nan)
    
recvs = recvs.reset_index()

first_timestamps = recvs.groupby("dest")["datetime"].transform("first")

hours_active = (recvs["datetime"] - first_timestamps).dt.total_seconds() / 3600.0

# Usual count per hour = C_all / T
recvs["usual_count_per_hour_as_dest"] = np.where(hours_active > 0, recvs["all_time_count_as_dest"] / hours_active, 0.0)

# Usual transaction amount per hour = Sum_all / T
recvs["usual_volume_per_hour_as_dest"] = np.where(hours_active > 0, all_time_sum / hours_active, 0.0)

# Time since the last transaction
recvs["time_since_last_tx_as_dest"] = recvs.groupby("dest")["datetime"].diff().dt.total_seconds()

In [20]:
recvs = recvs.drop(columns = ["amount", "orig"]).rename(columns = {"dest": "account"})
recvs.head()

,datetime,account,count_as_dest_1h,mean_amt_as_dest_1h,unique_orig_1h,count_as_dest_24h,mean_amt_as_dest_24h,unique_orig_24h,count_as_dest_7d,mean_amt_as_dest_7d,unique_orig_7d,all_time_count_as_dest,usual_amt_as_dest,usual_count_per_hour_as_dest,usual_volume_per_hour_as_dest,time_since_last_tx_as_dest
0,2025-02-04 16:32:28,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0.000000,0.000000,NaN
1,2025-02-04 17:26:29,0,1.0,336.273038,1.0,1.0,336.273038,1.0,1.0,336.273038,1.0,1,336.273038,1.110768,373.521425,3241.0
2,2025-02-05 01:19:07,0,NaN,NaN,NaN,2.0,211.046632,2.0,2.0,211.046632,2.0,2,211.046632,0.227855,48.088096,28358.0
3,2025-02-05 05:28:56,0,NaN,NaN,NaN,3.0,160.376563,2.0,3.0,160.376563,2.0,3,160.376563,0.231819,37.178391,14989.0
4,2025-02-09 19:35:44,0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,169.261125,2.0,4,169.261125,0.032506,5.501991,396408.0

In [21]:
df = df.sort_values("datetime")
sends = sends.sort_values("datetime")
recvs = recvs.sort_values("datetime")

In [22]:
# Attach orig complete past history
# First as an orig
df = pd.merge_asof(df, sends, on = "datetime", left_by = "orig", right_by = "account")
df = df.rename(columns = {c: f"orig_{c}" for c in sends.columns if c not in ["datetime", "account"]})
df = df.drop(columns = ["account"])
# Second as a dest
df = pd.merge_asof(df, recvs, on = "datetime", left_by = "orig", right_by = "account")
df = df.rename(columns = {c: f"orig_{c}" for c in recvs.columns if c not in ["datetime", "account"]})
df = df.drop(columns = ["account"])

In [23]:
# Attach dest complete past history
# First as an orig
df = pd.merge_asof(df, sends, on = "datetime", left_by = "dest", right_by = "account")
df = df.rename(columns = {c: f"dest_{c}" for c in sends.columns if c not in ["datetime", "account"]})
df = df.drop(columns = ["account"])
# Second as a dest
df = pd.merge_asof(df, recvs, on = "datetime", left_by = "dest", right_by = "account")
df = df.rename(columns = {c: f"dest_{c}" for c in recvs.columns if c not in ["datetime", "account"]})
df = df.drop(columns = ["account"])

In [24]:
df.head()

,type,category,orig,dest,old_balance,new_balance,is_fraud,payment_method,merchant_info.merchant_id,merchant_info.category,...,dest_mean_amt_as_dest_24h,dest_unique_orig_24h,dest_count_as_dest_7d,dest_mean_amt_as_dest_7d,dest_unique_orig_7d,dest_all_time_count_as_dest,dest_usual_amt_as_dest,dest_usual_count_per_hour_as_dest,dest_usual_volume_per_hour_as_dest,dest_time_since_last_tx_as_dest
0,2,2,2757,982,394437.711297,394176.204794,0,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,NaN,0.0,0.0,NaN
1,2,7,5274,3316,319338.243872,319075.661365,0,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,NaN,0.0,0.0,NaN
2,2,5,5539,9714,456079.479098,455716.291490,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,NaN,0.0,0.0,NaN
3,0,4,9843,10665,435461.552951,431760.321488,0,1,110.0,2.0,...,NaN,NaN,NaN,NaN,NaN,0,NaN,0.0,0.0,NaN
4,2,3,6751,9215,266064.478615,265913.074246,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,NaN,0.0,0.0,NaN

In [25]:
# Count transactions (orig -> dest)
df["pair_count_forward"] = df.groupby(["orig", "dest"]).cumcount().values

# Count transactions (dest -> orig)
reverse_edges = df[["datetime", "orig", "dest"]].copy()
reverse_edges["historical_count"] = reverse_edges.groupby(["orig", "dest"]).cumcount().values

# Orig acts as dest, dest acts as orig
reverse_edges = reverse_edges.rename(columns = {"orig": "temp_dest", "dest": "temp_orig"})

# Merge on datetime
df = pd.merge_asof(df, reverse_edges, on = "datetime", left_by = ["orig", "dest"], right_by = ["temp_orig", "temp_dest"], allow_exact_matches = False)

# If they have never interacted in reverse, fill with 0
df["pair_count_reverse"] = df["historical_count"].fillna(0).astype(int)
df = df.drop(columns = ["temp_orig", "temp_dest", "historical_count"])

In [26]:
df["amount_per_orig_usual_amt_as_orig"] = df["amount"] / df["orig_usual_amt_as_orig"]
df["amount_per_orig_usual_amt_as_dest"] = df["amount"] / df["orig_usual_amt_as_dest"]
df["amount_per_dest_usual_amt_as_orig"] = df["amount"] / df["dest_usual_amt_as_orig"]
df["amount_per_dest_usual_amt_as_dest"] = df["amount"] / df["dest_usual_amt_as_dest"]
df["flag_close_to_limit"] = ((df["amount"] >= 8500) & (df["amount"] < 10000)).astype(int)

In [27]:
cols_to_fill = df.columns[~df.columns.str.startswith("merchant_info.")]
df[cols_to_fill] = df[cols_to_fill].fillna(0)
df.columns.tolist()

['type',
 'category',
 'orig',
 'dest',
 'old_balance',
 'new_balance',
 'is_fraud',
 'payment_method',
 'merchant_info.merchant_id',
 'merchant_info.category',
 'merchant_info.risk_level',
 'merchant_info.avg_transaction',
 'datetime',
 'city_state',
 'postcode',
 'device',
 'ip_subnet',
 'hour_sin',
 'hour_cos',
 'day_sin',
 'day_cos',
 'month_sin',
 'month_cos',
 'amount',
 'orig_count_as_orig_1h',
 'orig_mean_amt_as_orig_1h',
 'orig_unique_dest_1h',
 'orig_count_as_orig_24h',
 'orig_mean_amt_as_orig_24h',
 'orig_unique_dest_24h',
 'orig_count_as_orig_7d',
 'orig_mean_amt_as_orig_7d',
 'orig_unique_dest_7d',
 'orig_all_time_count_as_orig',
 'orig_usual_amt_as_orig',
 'orig_usual_count_per_hour_as_orig',
 'orig_usual_volume_per_hour_as_orig',
 'orig_time_since_last_tx_as_orig',
 'orig_count_as_dest_1h',
 'orig_mean_amt_as_dest_1h',
 'orig_unique_orig_1h',
 'orig_count_as_dest_24h',
 'orig_mean_amt_as_dest_24h',
 'orig_unique_orig_24h',
 'orig_count_as_dest_7d',
 'orig_mean_amt_as_dest_7d',
 'orig_unique_orig_7d',
 'orig_all_time_count_as_dest',
 'orig_usual_amt_as_dest',
 'orig_usual_count_per_hour_as_dest',
 'orig_usual_volume_per_hour_as_dest',
 'orig_time_since_last_tx_as_dest',
 'dest_count_as_orig_1h',
 'dest_mean_amt_as_orig_1h',
 'dest_unique_dest_1h',
 'dest_count_as_orig_24h',
 'dest_mean_amt_as_orig_24h',
 'dest_unique_dest_24h',
 'dest_count_as_orig_7d',
 'dest_mean_amt_as_orig_7d',
 'dest_unique_dest_7d',
 'dest_all_time_count_as_orig',
 'dest_usual_amt_as_orig',
 'dest_usual_count_per_hour_as_orig',
 'dest_usual_volume_per_hour_as_orig',
 'dest_time_since_last_tx_as_orig',
 'dest_count_as_dest_1h',
 'dest_mean_amt_as_dest_1h',
 'dest_unique_orig_1h',
 'dest_count_as_dest_24h',
 'dest_mean_amt_as_dest_24h',
 'dest_unique_orig_24h',
 'dest_count_as_dest_7d',
 'dest_mean_amt_as_dest_7d',
 'dest_unique_orig_7d',
 'dest_all_time_count_as_dest',
 'dest_usual_amt_as_dest',
 'dest_usual_count_per_hour_as_dest',
 'dest_usual_volume_per_hour_as_dest',
 'dest_time_since_last_tx_as_dest',
 'pair_count_forward',
 'pair_count_reverse',
 'amount_per_orig_usual_amt_as_orig',
 'amount_per_orig_usual_amt_as_dest',
 'amount_per_dest_usual_amt_as_orig',
 'amount_per_dest_usual_amt_as_dest',
 'flag_close_to_limit']

In [28]:
df.to_csv("data_for_classifier.csv", index = False)